
# --- !Ups

create table "users" (
  "id"            bigint generated by default as identity(start with 1) not null primary key,
  "email"         varchar(255) not null unique,
  "sha_password"  varchar(255) not null
);

create table "blog_posts" (
  "id"            bigint generated by default as identity(start with 1) not null primary key,
  "subject"       varchar(255) not null,
  "content"       text,
  "user_id"       bigint,
  "comment_count" bigint
);

create table "post_comments" (
  "id"            bigint generated by default as identity(start with 1) not null primary key,
  "blog_post_id"  bigint,
  "user_id"       bigint,
  "content"       text
);

alter table "blog_posts" add constraint "fk_blog_post_user_1" foreign key ("user_id") references "users" ("id") on delete restrict on update restrict;
create index "ix_blog_post_user_1" on "blog_posts" ("user_id");
alter table "post_comments" add constraint "fk_post_comment_blogpost_2" foreign key ("blog_post_id") references "blog_posts" ("id") on delete restrict on update restrict;
create index "ix_post_comment_blogpost_2" on "post_comments" ("blog_post_id");
alter table "post_comments" add constraint "fk_post_comment_user_3" foreign key ("user_id") references "users" ("id") on delete restrict on update restrict;
create index "ix_post_comment_user_3" on "post_comments" ("user_id");



# --- !Downs

drop table if exists "blog_posts";

drop table if exists "post_comments";

drop table if exists "app_users";

